apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: nodejs-me
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: marcossb/nodejs-test
