apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-rc
spec:
  replicas: 3
  selector:
    app: nodejs-test
  template:
    metadata:
      labels:
        app: nodejs-test
    spec:
      containers:
      - name: nodejs
        image: marcossb/nodejs-test
        ports:
        - containerPort: 8080
