apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs
spec:
  replicas: 3
  selector:
    app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: marcossb/nodejs-test
        ports:
        - name: http
          containerPort: 8080
