apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sleep-cronjob
spec:
  schedule: "0,15,30,45 * * * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: sleep-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: marcossb/job
