apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  volumes:
  - hostPath:
      path: /var/mongodb/data
      type: ""
    name: mongodb-data
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
